name: ImcSegmentationPipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - tifffile
  - jupyter
  - libtiff
  - matplotlib
  - notebook
  - numpy
  - python=3.8
  - scikit-image
  - scipy
  - git
  - pip:
        - imctools>=2.1
