name: imctools
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pip
  - tifffile
  - jupyter
  - libtiff
  - matplotlib
  - notebook
  - numpy
  - python=3.6.6
  - scikit-image
  - scipy
  - git
  - pip:
        - imctools==1.0.7
